name: 'Deploy to AWS S3'
description: 'Deploy to AWS S3'
inputs:
   bucket: 
      description: 'The s3 bucket name'
      required: true
   bucket-region:
      description: 'region of the bucket'
      required: false
      default: 'us-east-1'
   dist-folder:
      description: 'folder containing the deploying files'
      required: true
outputs:
   website-url:
      description: 'The Url of the website'
runs:
 using: 'node20'
 main: 'main.js'